language: python
python:
 - "2.7"
addons:
  apt:
    packages:
      - oracle-java8-set-default  # install Java8 as required by vnu.jar

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root _build/

deploy:
  provider: surge
  project: ./static/
  domain: example.surge.sh  
